# Configuración optimizada de Alacritty para Neovim
# Formato TOML moderno

[general]
import = ["~/.config/alacritty/themes/gruvbox.toml"]
live_config_reload = true

# Environment variables
[env]
TERM = "xterm-256color"

# Window settings
[window]
padding.x = 12
padding.y = 12
dynamic_padding = false
decorations = "Buttonless"
startup_mode = "Fullscreen"  # Opciones: "Windowed", "Maximized", "Fullscreen"
title = "Alacritty"
dynamic_title = true
opacity = 0.8
blur = true

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Font configuration
[font]
size = 14
builtin_box_drawing = true

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

# Colors - Usando tema Gruvbox importado
# Si quieres cambiar a Catppuccin Mocha, descomenta estas líneas y comenta el import de gruvbox
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"

# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"

# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"

# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"

# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"

# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"

# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"

# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"

# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"

# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

# Bell
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Mouse
[mouse]
hide_when_typing = false

# Key bindings optimizados para Neovim
[[keyboard.bindings]]
key = "A"
mods = "Alt"
chars = "\u0002"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "SearchForward"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

# Shell
[shell]
program = "/bin/zsh"
args = ["--login"]

# Environment variables
[env]
TERM = "xterm-256color"
