# Configuración optimizada de Alacritty para Neovim
# Copia este archivo a ~/.config/alacritty/alacritty.yml

# General settings
live_config_reload: true

# Window settings
window:
  padding:
    x: 12
    y: 12
  dynamic_padding: false
  decorations: buttonless # En macOS quita los botones
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true
  opacity: 0.95 # Transparencia sutil

# Scrolling
scrolling:
  history: 10000
  multiplier: 3

# Font configuration
font:
  # Fuentes recomendadas para programming (elige una):
  # JetBrains Mono, Fira Code, Cascadia Code, SF Mono, Hack
  normal:
    family: "JetBrains Mono"
    style: Regular
  bold:
    family: "JetBrains Mono"
    style: Bold
  italic:
    family: "JetBrains Mono"
    style: Italic
  bold_italic:
    family: "JetBrains Mono"
    style: Bold Italic

  size: 14.0

  # Ligatures support
  builtin_box_drawing: true

# Colors (Catppuccin Mocha theme)
colors:
  primary:
    background: "#1e1e2e"
    foreground: "#cdd6f4"
    dim_foreground: "#7f849c"
    bright_foreground: "#cdd6f4"

  cursor:
    text: "#1e1e2e"
    cursor: "#f5e0dc"

  vi_mode_cursor:
    text: "#1e1e2e"
    cursor: "#b4befe"

  search:
    matches:
      foreground: "#1e1e2e"
      background: "#a6adc8"
    focused_match:
      foreground: "#1e1e2e"
      background: "#a6e3a1"

  footer_bar:
    foreground: "#1e1e2e"
    background: "#a6adc8"

  hints:
    start:
      foreground: "#1e1e2e"
      background: "#f9e2af"
    end:
      foreground: "#1e1e2e"
      background: "#a6adc8"

  selection:
    text: "#1e1e2e"
    background: "#f5e0dc"

  normal:
    black: "#45475a"
    red: "#f38ba8"
    green: "#a6e3a1"
    yellow: "#f9e2af"
    blue: "#89b4fa"
    magenta: "#f5c2e7"
    cyan: "#94e2d5"
    white: "#bac2de"

  bright:
    black: "#585b70"
    red: "#f38ba8"
    green: "#a6e3a1"
    yellow: "#f9e2af"
    blue: "#89b4fa"
    magenta: "#f5c2e7"
    cyan: "#94e2d5"
    white: "#a6adc8"

  dim:
    black: "#45475a"
    red: "#f38ba8"
    green: "#a6e3a1"
    yellow: "#f9e2af"
    blue: "#89b4fa"
    magenta: "#f5c2e7"
    cyan: "#94e2d5"
    white: "#bac2de"

  indexed_colors:
    - { index: 16, color: "#fab387" }
    - { index: 17, color: "#f5e0dc" }

# Bell
bell:
  animation: EaseOutExpo
  duration: 0
  color: "#ffffff"

# Mouse
mouse:
  hide_when_typing: false

# Key bindings optimizados para Neovim
key_bindings:
  # Tmux integration (si usas tmux)
  - { key: A, mods: Alt, chars: "\x02" }

  # Quick commands
  - { key: T, mods: Command, action: CreateNewWindow }
  - { key: W, mods: Command, action: Quit }

  # Copy/Paste
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }

  # Search
  - { key: F, mods: Command, action: SearchForward }

  # Font size
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: Key0, mods: Command, action: ResetFontSize }

# Shell
shell:
  program: /bin/zsh
  args:
    - --login

# Environment variables
env:
  TERM: xterm-256color
# Debug (comentar en producción)
# debug:
#   render_timer: false
#   persistent_logging: false
#   log_level: Warn
#   print_events: false
